import Head from 'next/head'
import React from 'react'

import { Box, Center, Flex, Heading, Text, VStack } from '@chakra-ui/react'

import BoardPanel from 'src/components/layout/BoardPanel'
import PlayerPanel from 'src/components/layout/PlayerPanel'
import SummaryPanel from 'src/components/layout/SummaryPanel'
import CardsPanel from 'src/components/layout/CardsPanel'
import HeadingPanel from 'src/components/layout/HeadingPanel'
import ChipsPanel from 'src/components/layout/ChipsPanel'

export default class Play extends React.Component<{}, {}> {
  public constructor(props: {}) {
    super(props);
  }

  public render() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeadingPanel flex="1 1 100%" />
        <Flex justifyContent="center" align="stretch" wrap="wrap">
          <CardsPanel flex="0 1 100%" />
          <ChipsPanel flex="0 1 100%" />
        </Flex>
        <SummaryPanel />
      </>
    )
  }
}


