import Head from 'next/head'
import React from 'react'

import { Flex } from '@chakra-ui/react'

import BoardPanel from 'src/components/layout/BoardPanel'
import PlayerPanel from 'src/components/layout/PlayerPanel'
import SummaryPanel from 'src/components/layout/SummaryPanel'

export default class Play extends React.Component<{}, {}> {
  public constructor(props: {}) {
    super(props);
  }

  public render() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Flex justifyContent="center" wrap="wrap">
          <BoardPanel flex="1 1 auto" w="300px" />
          <PlayerPanel flex="1 1 auto" w="300px" />
        </Flex>
        <SummaryPanel />
      </>
    )
  }
}


